const listCerts = require('../../lib/listCerts')

module.exports = {
  cmd: 'list-certs',
  desc: 'List certificates',
  builder: {
    backends: {
      description: 'List certificates generated by comma separated list of backends',
      examples: 'certbot,thirdparty'
    }
  },
  handler: (argv) => {
    listCerts(argv).catch((e) => {
      console.error(e)
      process.exit(1)
    })
  }
}
