version: '3.7'
services:
  certcacheserver:
    container_name: certcacheserver
    image: 93million/certcache
    restart: "unless-stopped"
    ports:
      - '53:53/udp'
      - '53:53/tcp'
      - '80:80/tcp'
      - '4433:4433/tcp'
    volumes:
      - ./certcacheserver/cahkeys/:/certcache/cahkeys/:rw
      - ./certcacheserver/cache/:/certcache/cache/:rw
    env_file:
      ./.env
    environment:
      CERTCACHE_CERTBOT_EMAIL: ${CERTCACHE_CERTBOT_EMAIL}
    command: ['serve']
